
import React from 'react';

const IconWrapper: React.FC<{ children: React.ReactNode, className?: string }> = ({ children, className = "w-4 h-4" }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        {children}
    </svg>
);

export const FileIcon: React.FC = () => (<IconWrapper className="w-4 h-4 mr-1.5 flex-shrink-0"><path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m-1.5 1.5-3 3m0 0v11.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5" /></IconWrapper>);
export const FolderIcon: React.FC = () => (<IconWrapper className="w-4 h-4 mr-1.5 flex-shrink-0"><path strokeLinecap="round" strokeLinejoin="round" d="M2.25 12.75V12A2.25 2.25 0 014.5 9.75h15A2.25 2.25 0 0121.75 12v.75m-8.69-6.44l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z" /></IconWrapper>);

export interface MasterplanNode { id: string; title: string; icon: React.ComponentType; content?: string; children?: MasterplanNode[]; }

const LOGIC_XO_HIERARCHY: MasterplanNode[] = [
    {
        id: 'phase1', title: 'Phase 1: Foundation', icon: FolderIcon, children: [
            { id: 'p1_pos', title: 'Strategic Positioning', icon: FileIcon, content: `## Strategic Positioning and Vision\nOPUS MAGNUM MEDIA positions itself as the Marketing Operations Platform of the next generation, fusing strategic precision with creative excellence. The core philosophy **"Where Strategy Meets Art"** manifests in an intelligent system that uses AI as a tool to amplify human creativity – not replace it.\n\n### The Fundamental Value Proposition\nFor users, OPUS MAGNUM MEDIA means the democratization of Enterprise Marketing Capabilities. Professionals gain access to features usually reserved for large corporations with multi-million dollar budgets: unified customer data, predictive analytics, multi-channel orchestration, and AI-powered content generation.` },
            { id: 'p1_arch', title: 'Technical Architecture', icon: FileIcon, content: `## Technical Architecture and Infrastructure\n### Google Cloud as Foundation\nThe Google Cloud Platform offers decisive advantages for marketing applications:\n* **Native Marketing Connectors:** Direct integrations to Google Ads, Google Analytics 360, Campaign Manager, etc.\n* **Identity Graph & 1st-Party Data:** Google's Identity technology allows matching your own customer data with Google user profiles.\n* **Marketing Analytics Jumpstart:** Pre-built solutions for integrating first-party data with BigQuery ML and Vertex AI.\n\n### Gemini 2.5 Pro in Frontend: The AI Engine\n* **Native Multimodality:** Understands and combines text, images, videos, and audio.\n* **Extended Context Windows:** Processes up to 1 million tokens for complex reasoning processes.\n* **Real-time Google Search Grounding:** Access to current data through live Google Search.\n* **Thinking Mode for Complex Queries:** Extended reasoning mode for deep analyses.` },
            { id: 'p1_core', title: 'Core Functionalities', icon: FileIcon, content: `## Core Functionalities and Workflows\n1.  **Content Creation & Production:** Multi-Format Content Creation (Blogs, Social Media, Email), Imagen 4 for Visuals, Veo for Video Animation, and a Quality Control Framework.\n2.  **Data Management & Analytics:** Unified Customer 360 in BigQuery, Predictive Analytics (Propensity Modeling, LTV, Churn Prediction), Attribution Optimization.\n3.  **Campaign Management & Automation:** End-to-End Campaign Orchestration, integrated Marketing Calendars, Template-based workflows for repeatable campaigns (Welcome Series, Abandoned Cart etc.).\n4.  **AI-Powered Personalization:** Enterprise-level Hyper-Personalization, Real-time Dynamic Content Personalization, AI-Driven Audience Segmentation.\n5.  **Collaboration & Workflow Management:** Integrated Approval Workflows, Online Proofing, Version Control, and a central Digital Asset Management (DAM).\n6.  **Conversational AI:** Gemini-powered Chatbots for Support, Lead Qualification, and Appointment Scheduling.` },
            { id: 'p1_skills', title: 'Competencies & Training', icon: FileIcon, content: `## Required Skills and Competencies\n### For Platform Administrators:\n* **Technical Proficiency:** Marketing Technology Stack (MAP, CRM, CMS), Google Cloud, BigQuery, Vertex AI, Gemini APIs, SQL, ETL/ELT.\n* **Process Design:** Workflow Design, SLA Definition, Change Control, Agile/Scrum.\n\n### For Marketing Operations Managers:\n* **Strategic Skills:** Marketing Strategy Translation, Campaign Orchestration, Vendor & Budget Management.\n* **Data-Driven Decision Making:** Funnel Analytics, A/B Testing, KPI Tracking, Data Visualization.\n\n### Curriculum Structure for User Training:\n* **Module 1:** Platform Fundamentals (1-2 Weeks)\n* **Module 2:** Content Creation & Management (2-3 Weeks)\n* **Module 3:** Marketing Automation (2-3 Weeks)\n* **Module 4:** Analytics & Optimization (2 Weeks)\n* **Module 5:** AI Strategy & Advanced Use Cases (1-2 Weeks)\n* **Module 6:** Hands-On Projects (2-3 Weeks)` },
            { id: 'p1_ops', title: 'Operations & Workflows', icon: FileIcon, content: `## Essential Workflows for Daily Operations\n### Daily Operations Workflow\n* **Morning Briefing Dashboard:** KPI Performance, Active Campaign Status, Content Production Pipeline, Priority Tasks.\n* **Content Production Cycle:** Ideation → Brief Creation → Content Generation → Review & QA → Optimization → Publishing → Monitoring.\n\n### Weekly Operations Workflow\n* **Campaign Planning & Coordination:** Weekly Planning, Execution Sprints, Week Review.\n* **Reporting & Analytics Cycle:** Performance Reports, Attribution Analysis, Lead Quality Assessment.\n\n### Monthly Strategic Workflow\n* **Strategic Review & Planning:** Monthly Business Review, Campaign Retrospectives, Resource Capacity Planning.\n* **Data Quality & Maintenance:** CRM Data Cleanup, Segmentation Review, Compliance Audits.` },
            { id: 'p1_usp', title: 'USPs & Roadmap', icon: FileIcon, content: `## Competitive Advantages & Differentiators\n1.  **Unified AI-Native Architecture:** A coherent, ground-up AI-native platform.\n2.  **Google Ecosystem Integration:** Seamless data flow with Google Workspace, Analytics, Ads, and Cloud.\n3.  **Multimodal Native Capabilities:** Surpasses competing solutions in complex, cross-channel tasks.\n4.  **Real-time Intelligence:** Google Search Grounding delivers current data.\n5.  **Enterprise-Grade Security & Compliance:** Google Cloud's security infrastructure.\n\n## Implementation Roadmap (30-60-90 Day Plan)\n* **30 Days (Foundation):** Platform Setup, Team Onboarding, Data Source Integration.\n* **60 Days (Expansion):** Advanced Automation, Predictive Analytics, Cross-Channel Campaign Launch.\n* **90 Days (Optimization):** AI Model Fine-Tuning, Advanced Personalization, ROI Measurement.` },
            { id: 'p1_arch_overview', title: 'Architecture Overview', icon: FileIcon, content: `## Architecture Overview: The Four Pillars\n*   **Pillar 1: Data Foundation Layer (BigQuery):** Central data repository for all marketing operations.\n*   **Pillar 2: AI Intelligence Layer (Vertex AI + Gemini):** AI core for Content, Insights, and Automation.\n*   **Pillar 3: Automation & Orchestration Layer (Cloud Functions):** Process Automation and System Integration.\n*   **Pillar 4: Activation & Delivery Layer (APIs):** Data Activation and Multi-Channel Delivery.\n\n### Technology Stack Overview\n[TABLE]\nService | Purpose | Pricing Model\n---|---|---\nBigQuery | Data Warehouse | Pay-per-query ($5/TB)\nVertex AI | ML Platform | Pay-per-use (Training + Prediction)\nCloud Functions | Serverless Compute | Pay-per-invocation\nCloud Storage | Object Storage | Pay-per-GB stored\n[/TABLE]` },
        ]
    },
    {
        id: 'phase2', title: 'Phase 2: Cloud Setup', icon: FolderIcon, children: [
            { id: 'p2_billing', title: 'Organization & Billing', icon: FileIcon, content: `## 1. Google Cloud Organization & Billing\n*   **Create Google Cloud Organization:** Go to the Google Cloud Console and create an Organization under "Identity & Organization".\n*   **Activate Cloud Billing:** Create a billing account for the organization and link it.` },
            { id: 'p2_iam', title: 'Project Structure & IAM', icon: FileIcon, content: `## 2. Project Structure & Access (IAM)\n*   **Create Projects:** Create a separate project per main function (e.g., 'marketing-data-warehouse', 'ai-intelligence-hub').\n*   **Naming:** Use a clear schema: \`opus-[env]-[function]-[region]\`.\n*   **Assign Access/Roles (IAM):** Create user groups (e.g., 'marketing-admins', 'marketing-analysts') and assign minimum rights per project.` },
            { id: 'p2_apis', title: 'APIs & Services', icon: FileIcon, content: `## 3. Activate Core APIs & Services\nThe necessary APIs must be activated per project:\n*   BigQuery API\n*   Vertex AI API\n*   Cloud Functions API\n*   Cloud Storage API\n*   Pub/Sub API\n*   Cloud Scheduler API\n*   Secret Manager API` },
            { id: 'p2_security', title: 'Resources & Security', icon: FileIcon, content: `## 4. Resource Structure and 5. Security\n*   **Environments:** Create environments for 'development', 'staging', 'production'.\n*   **Audit Logging:** Activate Cloud Audit Logs project-wide (active by default).\n*   **Secret Manager:** Use the Secret Manager for API Keys and Service Account keys.` },
            { id: 'p2_accounts', title: 'Service Accounts & Check', icon: FileIcon, content: `## 6. Service Accounts & 7. Quick Check\n*   **Dedicated Service Accounts:** Create a Service Account per Use Case (e.g., 'data-ingestion-sa', 'ai-processing-sa').\n*   **"Least Privilege" Principle:** Assign only the necessary rights.\n*   **Health Check:** Check all projects with the Cloud Resource Manager and assigned roles with IAM & Admin.` },
        ]
    },
    {
        id: 'phase3', title: 'Phase 3: Data & AI', icon: FolderIcon, children: [
            { id: 'p3_sources', title: 'Data Source Integration', icon: FileIcon, content: `## 1. Integration of Marketing Data Sources\n*   **Google Analytics 4 (GA4):** Link via Admin > Property > BigQuery Links.\n*   **Google Ads:** Connect via the BigQuery Data Transfer Service.\n*   **External Data Sources/CRM:** Use Cloud Functions to automatically load data via API (e.g., HubSpot, Salesforce) into BigQuery.` },
            { id: 'p3_identity', title: 'User Identity Graph', icon: FileIcon, content: `## 2. Building a User Identity Graph\n*   **Consolidation:** Merge User IDs (CRM-ID, GA Client ID, Email) via unique keys.\n*   **Goal:** Linking Web Sessions, Transactions, and CRM Data into complete customer profiles in a dedicated BigQuery Dataset.` },
            { id: 'p3_gemini', title: 'Gemini & Vertex AI', icon: FileIcon, content: `## 3. Connecting Gemini & Vertex AI\n*   **Activate Gemini 2.5 Pro:** Get an API Key from Google AI Studio or Vertex AI and store it in the Secret Manager.\n*   **Prepare Vertex AI:** Create a Notebook in Vertex AI Workbench and link it to your BigQuery project.\n*   **IAM for AI:** Ensure the Service Account has the roles \`roles/aiplatform.user\` & \`roles/bigquery.user\`.` },
            { id: 'p3_tests', title: 'Quick Tests', icon: FileIcon, content: `## 4. Quick Tests: Use Data and AI live\n*   **BigQuery Test:** Run first SQL Queries on imported GA4/Ads data.\n*   **Gemini Quick Test:** Write a simple prompt to generate content based on a BigQuery output.\n*   **Vertex AI Test:** Load a dataset from BigQuery and run an ML model (e.g., Churn Prediction).` },
        ]
    },
    { id: 'phase4', title: 'Phase 4: Automation', icon: FolderIcon, content: `## Phase 4: Automation & Workflow Integration\nIn this phase, core processes are automated.\n\n### 1. Workflow: Welcome/Onboarding Series\n*   **Goal:** Automated welcome emails for new contacts.\n*   **Process:** A Cloud Function is triggered by new contacts in BigQuery, calls the Gemini API for personalized text, and sends the email via an Email Platform API.\n\n### 2. Workflow: Lead Nurturing Drip Campaigns\n*   **Goal:** Automated multi-step campaigns for leads.\n*   **Process:** A daily trigger (Cloud Scheduler) starts a Cloud Function that retrieves segmented leads from BigQuery and generates and sends appropriate content via Gemini.\n\n### 3. Workflow: Abandoned Cart Recovery\n*   **Goal:** Recover lost shopping carts.\n*   **Process:** A BigQuery query identifies open shopping carts. A Cloud Function generates an individual reminder email and sends it.\n\n### 4. Management & Security\n*   All workflows are monitored via Cloud Logging and Monitoring.\n*   A Human-in-the-loop approach ensures the quality of AI-generated content.` },
    { id: 'phase5', title: 'Phase 5: Optimization', icon: FolderIcon, content: `## Phase 5: Review, Optimization, and Expansion\nExisting processes are reviewed and improved.\n\n### 1. Review & Performance Monitoring\n*   **Dashboard Setup:** Set up real-time dashboards in Data Studio/Looker for KPIs like Engagement and Conversion Rates.\n*   **Quality Loop:** Conduct regular manual reviews of AI-generated content.\n\n### 2. Continuous Improvement\n*   **A/B Testing:** Use Cloud Functions to play out different content variants and measure their performance.\n*   **AI Model Fine-Tuning:** Train own ML models with Vertex AI for Lead Scoring or Segmentation on your data.\n\n### 3. New Use Cases\n*   **Cross-Channel Activation:** Export Audiences directly to Google Ads Customer Match.\n*   **Event-Based Marketing:** Add workflows for occasions like birthdays or product launches.\n*   **Conversational AI:** Integrate Gemini-powered Chatbots.` },
    { id: 'phase6', title: 'Phase 6: Scaling', icon: FolderIcon, content: `## Phase 6: Scaling, Agentic AI, and Product Layering\nThe system is developed into an autonomous, scalable platform.\n\n### 1. Scaling & Performance Optimization\n*   Activate Autoscaling for Cloud Functions and Vertex AI.\n*   Optimize BigQuery costs through Query Optimization and Partitioning.\n*   Build a multi-tenant architecture.\n\n### 2. Agentic AI Capabilities\n*   Develop Gemini-based agents that independently analyze campaigns and propose or execute optimizations.\n*   Define "AI-in-the-Loop" processes where AI generates hypotheses and sets up experiments that are approved by a human.` },
    { id: 'phase7', title: 'Phase 7: Go-To-Market', icon: FolderIcon, content: `## Phase 7: Final Blueprint & Go-to-Market Beta\nThe platform is prepared for a productive launch.\n\n*   **1. Feature Finalization:** Define the final scope of functions and create product demos.\n*   **2. Beta Tests:** Conduct a Closed Beta with selected test users and gather systematic feedback.\n*   **3. Preparation:** Create official documentation, a Knowledge Base, and launch communication.\n*   **4. Compliance & Scaling:** Conduct a Security Audit and simulate load tests.\n*   **5. Product Iteration:** Implement a "Feature Request" process for direct user wishes.\n*   **6. Launch:** Open the platform to wider user groups.` },
    { id: 'abschluss', title: 'Conclusion', icon: FolderIcon, content: `## Conclusion: Review and Path to Ongoing Operation\nAfter completing the development phases, the focus shifts to sustainability and continuous evolution of the Project OS.\n\n### 1. Ongoing Operation (Run Phase)\n*   **Monitoring:** Set up regular health checks and automatic notifications.\n*   **Optimization:** Plan monthly reviews of your most important KPIs.\n*   **Community and Training:** Further expand the Knowledge Base and certification programs.\n\n### 2. Further Development & Vision\n*   **Intensify Agentic Loops:** The goal is stronger self-optimization of workflows.\n*   **Internationalization:** Prepare the system to connect multiple languages and new markets.\n*   **Product Expansion:** Develop accompanying tools and modules iteratively according to your users' needs.` },
];

export const MASTERPLAN_HIERARCHY: MasterplanNode[] = [
    ...LOGIC_XO_HIERARCHY,
];
